"""empty message

Revision ID: 20b30b0bd59a
Revises: 21cc4e21ca36
Create Date: 2024-01-22 18:53:53.816147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b30b0bd59a'
down_revision = '21cc4e21ca36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('play_count')

    # ### end Alembic commands ###
