"""added relationship

Revision ID: 7d0555ea2c9b
Revises: bcfb4c5497c7
Create Date: 2024-01-16 20:19:14.321466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0555ea2c9b'
down_revision = 'bcfb4c5497c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('song_id')

    # ### end Alembic commands ###
